// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJ05m5edVfmdfKiPb8aY0EedZt62QY3E',
    appId: '1:58252877818:web:0d574ed574af703ced8e43',
    messagingSenderId: '58252877818',
    projectId: 'moodle-app-clone',
    authDomain: 'moodle-app-clone.firebaseapp.com',
    storageBucket: 'moodle-app-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwIdNc3aXJzCS7qKnGuzf2DOtLK5aP14',
    appId: '1:58252877818:android:10c23ed05042c2e1ed8e43',
    messagingSenderId: '58252877818',
    projectId: 'moodle-app-clone',
    storageBucket: 'moodle-app-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBseacGnan3eUCU93rFrX3CyPmT8hFw0io',
    appId: '1:58252877818:ios:8e25b6f281c049a7ed8e43',
    messagingSenderId: '58252877818',
    projectId: 'moodle-app-clone',
    storageBucket: 'moodle-app-clone.firebasestorage.app',
    iosBundleId: 'com.example.moduleClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseacGnan3eUCU93rFrX3CyPmT8hFw0io',
    appId: '1:58252877818:ios:8e25b6f281c049a7ed8e43',
    messagingSenderId: '58252877818',
    projectId: 'moodle-app-clone',
    storageBucket: 'moodle-app-clone.firebasestorage.app',
    iosBundleId: 'com.example.moduleClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANJ05m5edVfmdfKiPb8aY0EedZt62QY3E',
    appId: '1:58252877818:web:5602db4d46e8bc88ed8e43',
    messagingSenderId: '58252877818',
    projectId: 'moodle-app-clone',
    authDomain: 'moodle-app-clone.firebaseapp.com',
    storageBucket: 'moodle-app-clone.firebasestorage.app',
  );
}
